### ISSUE TITLE
rpc_s_access_denied when running example

### ISSUE THREAD

**Issue by hackdefendr** [kanazux/wmi-query#1]
Using the basic example from the help dialog, I receive this error:

> Traceback (most recent call last):
>   File "/usr/local/bin/wmi-query", line 28, in <module>
>     main()
>   File "/usr/local/bin/wmi-query", line 15, in main
>     wmi.run()
>   File "/usr/local/lib/python2.7/dist-packages/wmi_query/wmi_query.py", line 77, in run
>     self.get_wmi_data()
>   File "/usr/local/lib/python2.7/dist-packages/wmi_query/wmi_query.py", line 29, in get_wmi_data
>     _wmi_data = wmi_conn.wmi_conn(self.host, self.user, self.password, self.domain, self.namespace, self.query)
>   File "/usr/local/lib/python2.7/dist-packages/wmi_query/wmi_conn.py", line 25, in wmi_conn
>     _interface = _dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login, wmi.IID_IWbemLevel1Login)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1056, in CoCreateInstanceEx
>     iInterface = scm.RemoteCreateInstance(clsid, iid)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1837, in RemoteCreateInstance
>     resp = self.__portmap.request(request)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 837, in request
>     answer = self.recv()
>   File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1299, in recv
>     raise DCERPCException(rpc_status_codes[status_code])
> impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_s_access_denied

Thanks!

**Comment by kanazux** [comment]
Hi @hackdefendr 

this error says that you accesses to the rpc server was denied.
Can you tell me wich version of the windows server you trying to connect, and check if the credentials is ok?
